title: さざんか会事件解説（障害者グループホームの勤務時間をめぐるさざんか会裁判）
logo: logo.png
description: 千葉県内の社会福祉法人さざんか会の従業員が、泊まり勤務中の夜勤時間帯の残業代支払いなどを求めた裁判について、代理人の黒葛原歩弁護士の解説をまとめています。原告本人もコメントを寄せています。本件訴訟は、労働時間性が認められ、原告が勝訴しました。
exclude_patterns: [_build, _00hikae, README.md, memo.txt]

html:
  announcement: 本ウェブサイトは、原告本人 <a class="reference external" href="https://x.com/tad61487"><i class="fa-brands fa-x-twitter"></i> @tad61487</a> さんと代理人 <a class="reference external" href="https://x.com/ATsZRA"><i class="fa-brands fa-x-twitter"></i> @ATsZRA</a> さんのポストを転載しています。
  favicon: "_static/favicon.png" 
  baseurl: https://minnanosaiban.github.io/sazankakai/
  use_multitoc_numbering: true
  home_page_in_navbar: true
  use_edit_page_button: false
  use_repository_button: false
  use_issues_button: false
  show_navbar_previous: false
  show_navbar_next: false

parse:
  myst_enable_extensions: 
    - amsmath
    - attrs_inline
    - colon_fence
    - deflist
    - dollarmath
    - fieldlist
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - strikethrough
    - substitution
    - tasklist